export const MainBoxStyle = {
    backgroundColor: "#03000569",
    backdropFilter:"blur(10px)",
    color: "white",
    width: "1000px",
    height: "660px",
    textAlign: "center",
    alignSelf:"center",
    padding: "20px",
    borderRadius: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    boxShadow: "rgb(0, 0, 0) 0px 22px 70px 4px;",
  }